
GET http://localhost:4000/api/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJpYXQiOjE3MDQwMjk4MzksImV4cCI6MTcwNDAzMzQzOX0.lepv9313lUng7jeSXP3N5WxonXJnj9bYJ9Ejazfdh7U
