
GET http://localhost:4000/api/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJpYXQiOjE3MDQxMjU1MTIsImV4cCI6MTcwNDEyOTExMn0.Ux1cC9WItndUlNu5ZqtK4NEZd9LTKmTv6xPdMdK9W7A